/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg2.projeto_tc;

import java.io.File;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Victor
 */
public class inicial extends javax.swing.JFrame {

    /**
     * Creates new form inicial
     */
    public inicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        EscolherArquivo = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        Converter = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("To grammar");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        EscolherArquivo.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        EscolherArquivo.setText("Escolher Arquivo");
        EscolherArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EscolherArquivoActionPerformed(evt);
            }
        });

        jTextField1.setEnabled(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        Converter.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        Converter.setText("Converter e Salvar");
        Converter.setEnabled(false);
        Converter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConverterActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabel1.setText("AFD para Gramática Regular");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Converter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EscolherArquivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(51, 51, 51))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EscolherArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(Converter, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EscolherArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EscolherArquivoActionPerformed
           JFileChooser Arquivo = new JFileChooser();
       Arquivo.setDialogTitle("Escolha um arquivo .JFF");
       Arquivo.setFileSelectionMode(JFileChooser.FILES_ONLY);
        FileNameExtensionFilter filter  = new FileNameExtensionFilter("JFF","jff"); 
       Arquivo.setFileFilter(filter);
   int escolha= Arquivo.showOpenDialog(this);
       File endereco = Arquivo.getSelectedFile();
        CarregarXml Carregar = new CarregarXml();
        Carregar.readXml(endereco.getPath());
      
        if(escolha == JFileChooser.APPROVE_OPTION){
                  jTextField1.setText(endereco.getPath());
                  Converter.setEnabled(true);
        }
      
        
    }//GEN-LAST:event_EscolherArquivoActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void ConverterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConverterActionPerformed
        CarregarXml carregar =  new CarregarXml();
        gerarGrammar(carregar.readXml(jTextField1.getText()));
    }//GEN-LAST:event_ConverterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Converter;
    private javax.swing.JButton EscolherArquivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
private void gerarGrammar(Automato automato){
    CarregarXml carregar =  new CarregarXml();
    List<String> variaveis = new ArrayList<>();
    List<String> transicoes = new ArrayList<>();
    int i=0;
    for (Estados A :  automato.getEstado()){
        if(A.getId()==0){
            variaveis.add("S");
        }else{
            variaveis.add(String.format("%c",'A'+i-1));
        }
        i++;
    }
    
    for(int j=0;j<automato.getTransition().size();j++){             
        transicoes.add(variaveis.get(automato.getTransition().get(j).getFrom())+""+automato.getTransition().get(j).getRead()
             +variaveis.get(automato.getTransition().get(j).getTo()));                                            
}
                for(int j=0;j<automato.getEstadofinal().size();j++){
                 transicoes.add(variaveis.get(automato.getEstadofinal().get(j).getId())+" <");
             }
       Grammar gramatica = new Grammar();
       List<String> left = new ArrayList<>();
    List<String> right = new ArrayList<>();
 for(i=0;i<transicoes.size();i++){
   left.add(transicoes.get(i).substring(0,transicoes.get(i).length()-2));
   right.add(transicoes.get(i).substring(transicoes.get(i).length()-2,transicoes.get(i).length()));
 }               
for(int x=0;x<transicoes.size();x++){
    System.out.println(left.get(x));
    System.out.println(right.get(x));
   // System.out.println(transicoes.get(x));
}

        gramatica.setLeft(left);
        gramatica.setRight(right);
        GerarXML salvar = new GerarXML();
        if(salvar.gerar(gramatica, true)){
            JOptionPane.showMessageDialog(null,"Arquivo Salvo!");
        }
    
}

}

